# Generated by Django 4.2.5 on 2023-10-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
