# Generated by Django 4.2.5 on 2023-10-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_trash_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='note',
        ),
    ]
