# Generated by Django 4.2.5 on 2023-10-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_trashnote_delete_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashnote',
            name='original_note',
        ),
        migrations.AddField(
            model_name='trashnote',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trashnote',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
