# Generated by Django 4.2.5 on 2023-10-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_trashnote_original_note_trashnote_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashnote',
            name='original_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
