# Generated by Django 4.2.5 on 2023-10-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_trashnote_original_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashnote',
            name='original_note',
        ),
    ]
