# Generated by Django 4.2.5 on 2023-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
